"use client";

import { X, Mail, Send } from "lucide-react";

interface EmailModalProps {
  isOpen: boolean;
  onClose: () => void;
  emailType: "tech" | "promotion";
  subject: string;
  body: string;
  recipient: string;
  onSend: () => void;
}

export default function EmailModal({
  isOpen,
  onClose,
  emailType,
  subject,
  body,
  recipient,
  onSend,
}: EmailModalProps) {
  if (!isOpen) return null;

  const bgColor = emailType === "tech" ? "bg-red-50" : "bg-green-50";
  const borderColor =
    emailType === "tech" ? "border-red-200" : "border-green-200";
  const textColor = emailType === "tech" ? "text-red-900" : "text-green-900";
  const buttonColor =
    emailType === "tech"
      ? "bg-red-600 hover:bg-red-700"
      : "bg-green-600 hover:bg-green-700";

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl max-w-3xl w-full max-h-[90vh] overflow-hidden">
        {/* Header */}
        <div
          className={`${bgColor} dark:${
            emailType === "tech" ? "bg-red-900/20" : "bg-green-900/20"
          } border-b-2 ${borderColor} dark:${
            emailType === "tech" ? "border-red-800" : "border-green-800"
          } p-6`}
        >
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Mail
                className={`w-7 h-7 ${textColor} dark:${
                  emailType === "tech" ? "text-red-400" : "text-green-400"
                }`}
              />
              <h2
                className={`text-2xl font-bold ${textColor} dark:${
                  emailType === "tech" ? "text-red-100" : "text-green-100"
                }`}
              >
                {emailType === "tech"
                  ? "📧 Tech Support Ticket"
                  : "🎁 Promotion Email"}
              </h2>
            </div>
            <button
              onClick={onClose}
              className="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200 transition-colors"
            >
              <X className="w-6 h-6" />
            </button>
          </div>
        </div>

        {/* Email Content */}
        <div className="p-6 overflow-y-auto max-h-[60vh]">
          {/* Recipient */}
          <div className="mb-4">
            <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1">
              To:
            </label>
            <div className="bg-gray-100 dark:bg-gray-700 px-4 py-2 rounded-lg text-gray-800 dark:text-gray-200">
              {recipient}
            </div>
          </div>

          {/* Subject */}
          <div className="mb-4">
            <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1">
              Subject:
            </label>
            <div className="bg-gray-100 dark:bg-gray-700 px-4 py-2 rounded-lg text-gray-800 dark:text-gray-200 font-medium">
              {subject}
            </div>
          </div>

          {/* Body */}
          <div className="mb-6">
            <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1">
              Message:
            </label>
            <div className="bg-gray-50 dark:bg-gray-700 px-4 py-3 rounded-lg text-gray-800 dark:text-gray-200 whitespace-pre-wrap border border-gray-200 dark:border-gray-600">
              {body}
            </div>
          </div>

          {/* AI Badge */}
          <div className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400">
            <span className="inline-block px-3 py-1 bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 rounded-full font-medium">
              ✨ AI-Generated by Gemini 2.0 Flash
            </span>
          </div>
        </div>

        {/* Footer Actions */}
        <div
          className={`border-t border-gray-200 dark:border-gray-700 p-6 flex gap-4 justify-end ${bgColor} dark:${
            emailType === "tech" ? "bg-red-900/10" : "bg-green-900/10"
          }`}
        >
          <button
            onClick={onClose}
            className="px-6 py-3 bg-gray-200 hover:bg-gray-300 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-800 dark:text-gray-200 rounded-lg font-semibold transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={onSend}
            className={`${buttonColor} text-white px-8 py-3 rounded-lg font-semibold transition-colors shadow-lg hover:shadow-xl flex items-center gap-2`}
          >
            <Send className="w-5 h-5" />
            Send Email
          </button>
        </div>
      </div>
    </div>
  );
}
